//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler aufgetreten! Gnome rücken in Scharen aus um diesen zu beheben. Falls Eisenschmiede morgen noch steht, probieren sie es wieder! ähnelt.
        /// </summary>
        internal static string COMMON_ERROR {
            get {
                return ResourceManager.GetString("COMMON_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler aufgetreten!\nBitte wenden Sie sich an den System-Administrator! ähnelt.
        /// </summary>
        internal static string ERROR_COMMON {
            get {
                return ResourceManager.GetString("ERROR_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Anmeldung!\nBenutzer und/oder Passwort falsch! ähnelt.
        /// </summary>
        internal static string ERROR_LOGIN {
            get {
                return ResourceManager.GetString("ERROR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Registrieren!\nBitte wenden Sie sich an den System-Administrator! ähnelt.
        /// </summary>
        internal static string ERROR_REGISTER {
            get {
                return ResourceManager.GetString("ERROR_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username unbekannt!\nBitte melden Sie sich erneut an! ähnelt.
        /// </summary>
        internal static string ERROR_UNKNOWN_USER {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige Pack-Nummer! Bitte wählen Sie eines der angezeigten Packs aus! ähnelt.
        /// </summary>
        internal static string INVALID_PACK_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_PACK_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldung erfolgreich ähnelt.
        /// </summary>
        internal static string SUCCESS_LOGIN {
            get {
                return ResourceManager.GetString("SUCCESS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung erfolgreich ähnelt.
        /// </summary>
        internal static string SUCCESS_REGISTER {
            get {
                return ResourceManager.GetString("SUCCESS_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Username existiert bereits!\nBitte wählen Sie einen neuen! ähnelt.
        /// </summary>
        internal static string WARNING_USERNAME_EXISTS {
            get {
                return ResourceManager.GetString("WARNING_USERNAME_EXISTS", resourceCulture);
            }
        }
    }
}
