//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hearthstone.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCardCollection
    {
        public int ID_User { get; set; }
        public int ID_Card { get; set; }
        public int NumberOfCards { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual User User { get; set; }
    }
}
