//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hearthstone.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualPurchase
    {
        public int ID { get; set; }
        public int ID_User { get; set; }
        public int ID_CardPack { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int NumberOfPacks { get; set; }
    
        public virtual CardPack CardPack { get; set; }
        public virtual User User { get; set; }
    }
}
